language: python

python:
- '3.5'

install:
- pip install -r requirements.txt

services:
- postgresql

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=core.settings

script:
- coverage run --source=app manage.py test --settings=core.settings
- flake8 .

after_success: coveralls

notifications:
  slack: teamtaverna:iP55LweubU8UOBgu9e0cTeED

deploy:
  provider: heroku
  api_key:
    secure: CbUfdzEjhmzvedJGh/PUFZDsnJucro3ojwfaWjli/BZ+1s8WFv4JXGPhywJEdXyKABFm/qQeOVVDt8YMO5HSknUXaUuwA6F6XDEoQMr8J8sPprfU1wXiMzZ35IuNKHsXhV2eCep7JtU3gG6fA0KeOgjqwwZESd1y+HYWo792O3ilfUqH40aIjPTkYUFoXiweovhFycOK8P/O1z1wc3rT42zpPNef2i6y+/qCyQQD8zH7kibhKqUgTsILJtTogZ6Nuqa/bGQHWbTCsNl/udoNHknmBIfdEc2xiJnQKpsTJGOBphmqb2SnyO8Srop8qmYemm+6spDT1Uw4/8zPaKRhbwNXCAUvrII9jiUQXFbmfXfH3YmYjMhrbxU1Ieaujl8zYea6fTAaBmn3kdZLwhdFQQXosQrZW6y2pxxtrFYA52Df5tTpf5deFmJIAlwR9hI/cq4KY0ZfjnVRUOeTmvduKhmI+C6xZtlpYUfnCZ9msAuuvsxUJG7SisTilEKs6OULYuzHP9N5YlBfQ7EvO1FgsJi86/CBo/4/BEq5xDvMpOX55hwBnessT/Yc4nbu72yXO2iTb46SmS9ZhtttQx2QDv2E/yA6WCU7kLdtfprxT0n0q6haIyw7qNfAnEVHzHmASI9Vazu6BPSs1VsRRTGf1wSJc+masEdCa7RkHI4jatM=
  app:
    master: taverna-core
    staging: taverna-core-staging
  run:
  - python manage.py migrate --noinput

env:
  global:
    secure: RaLQWaDnTVFsim/pnaaAK0PyBSkSpEAYCljIbDrcRuTIMKBDpde7rgNWNn7FK1O811Ff8YCXI33J/iCNSRozDJC2eZqHVPvRvGY2tipii6tpI22J7EtakuLqRrbAlyHsvZQXIUGxJ8GAF6VSx8CSc/SDZweSNP5FGY+vfs9nDrlWr0+1WR62XoW6VLiugkioXZnTYuIIAQI1ZNSqtNXGlAy2CqiHeQAexmMrfXLz3ByFtaOAYCv2LsOBebz4t9IZd0owWFHIXgVp6ryikg5D+U8gayuNAxF57V+x4+k5r/krXj0xuFipqhorz06Ikm8YmefcXoSP6intNZZ47PNF+2JriM98oum2UfLMH9PMlb9eaORYyhZVIuTBuoRxWYwledmRSXtGX3Q6HDSIXyE1Ek87gw3tzE8Z3sWyeVNQl5rMa1MVN7m+GzYMIdWrpHujTj2haRP0rSoJfJl6RdOMx58Tk9PQYmtmuLWCOxPvb/x8ZtzQWlNZWbOBh+l4GUHifOC2L0+zD85SZeimacUK+s4esSZ6o5WkzeWvNfUiw4Uy4ON8NHWLFj386d76cf85aWNSo6xgKpJP05qEnjSNnJ+xM898Z5Ds7t8Y+zLtlmDePmaNumgciClLijWBc8wgOvcz+x1YlrhR1ZB/r1TkzMJAJmdPPiC/TDK5OtT7y6A=
