language: python

python:
- '3.5'

install:
- pip install -r requirements.txt

services:
- postgresql

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=core.settings

script:
- coverage run --source=app manage.py test --settings=core.settings
- flake8 .

after_success: coveralls

notifications:
  slack: teamtaverna:iP55LweubU8UOBgu9e0cTeED

deploy:
  provider: heroku
  api_key:
    secure: CbUfdzEjhmzvedJGh/PUFZDsnJucro3ojwfaWjli/BZ+1s8WFv4JXGPhywJEdXyKABFm/qQeOVVDt8YMO5HSknUXaUuwA6F6XDEoQMr8J8sPprfU1wXiMzZ35IuNKHsXhV2eCep7JtU3gG6fA0KeOgjqwwZESd1y+HYWo792O3ilfUqH40aIjPTkYUFoXiweovhFycOK8P/O1z1wc3rT42zpPNef2i6y+/qCyQQD8zH7kibhKqUgTsILJtTogZ6Nuqa/bGQHWbTCsNl/udoNHknmBIfdEc2xiJnQKpsTJGOBphmqb2SnyO8Srop8qmYemm+6spDT1Uw4/8zPaKRhbwNXCAUvrII9jiUQXFbmfXfH3YmYjMhrbxU1Ieaujl8zYea6fTAaBmn3kdZLwhdFQQXosQrZW6y2pxxtrFYA52Df5tTpf5deFmJIAlwR9hI/cq4KY0ZfjnVRUOeTmvduKhmI+C6xZtlpYUfnCZ9msAuuvsxUJG7SisTilEKs6OULYuzHP9N5YlBfQ7EvO1FgsJi86/CBo/4/BEq5xDvMpOX55hwBnessT/Yc4nbu72yXO2iTb46SmS9ZhtttQx2QDv2E/yA6WCU7kLdtfprxT0n0q6haIyw7qNfAnEVHzHmASI9Vazu6BPSs1VsRRTGf1wSJc+masEdCa7RkHI4jatM=
  app:
    master: taverna-core
    staging: taverna-core-staging
  run:
  - python manage.py migrate --noinput

env:
  global:
    secure: Ht8QdJoisRYxjY8MPzNkUaNuJ1w6K+ZiBmhChI7H0A5K3J7BVTXZUCN8FZzD32axbMPopZJWJKjxpJco3JFUPgfVJV8nFmx8PuT8Domrc6yehz1khVdIc41RVZIbtkArsNU4edslGvSMAdSqKZIbCgg18JMztvlltHqln9kd0R44WqaBbz0vK8Zo77YFWV9yOnl6CnqOGLQXdyLTrGyAIVhLdLGmOMqNI2RVXb8mdRSlxRihky70CE8OFjEg0ayiKd2ITfaVrs4V1YruYKFB1Atx5oWBmvRg7kex11YRg3Pb86RoScmHmip4lQ7D2jHODseHpRNs1OKOyhyo4vGeibIboo/4fHN2m6c3oBdCU0LyjjjFyKxmw+wA4yZzzuPrLiIG3aL8aGXBZJ6sXEH9UDzHKcjWnjjFBYOrsppCGIsNtLkCz6QbNnF50Wwovytg7UDMIUqAZoEAyF1gRkrh7sOU+3+eTjxBf78/wzNV7UangKRPsbY8M0I58TSWwlD6zC+qMLW4dDtrV8WBged8cZ7W22fbXAIvXmykCa1mLBsToPbv5UuSzYJ0xSR05hmZ1J+Q/nxATTX2hQefQ4Ft/25d66upAFEHjzknm14l1m89g5Xf1byfJXoY4nDg0eOC+gajSO0Ujnx9MeNES0xhhj4wUrR6bpy+lS3snuGdJis=
